### ISSUE TITLE
cannot find visualization module and e.g. plot_mdf_surface in repo

### ISSUE THREAD

**Issue by shill1729** [layer6ai-labs/implicit-manifolds#1]
Hi,
First of all, interesting paper.

Now, `from visualization import plot_mdf_surface` is used in the notebook `geospatial.ipynb` but I cannot find the module anywhere in the repo. Am I missing something obvious? I was curious to see the implementation of `plot_mdf_surface` and the calls to the marching cubes algorithm in practice.

**Comment by blross** [comment]
Hi Sean,

Thanks for your interest in the code. I'm sorry for the slow response; I'm now watching the repo, so I should respond faster if you have any further questions.

A couple of modules were omitted from the notebooks folder for the camera-ready version of the repo. Things should work now.

Brendan
